# Generated by Django 5.1.4 on 2024-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
